-- Paladin
QUICKHEAL_SPELL_HOLY_LIGHT = 'Holy Light';
QUICKHEAL_SPELL_FLASH_OF_LIGHT = 'Flash of Light';
QUICKHEAL_SPELL_HOLY_SHOCK = 'Holy Shock';

QUICKHEAL_SPELL_HEALING_TOUCH = 'Healing Touch';
QUICKHEAL_SPELL_REGROWTH = 'Regrowth';
QUICKHEAL_SPELL_REJUVENATION = 'Rejuvenation';

FILTER_MTLIST_SHOW = 'Main Tanks';
FILTER_MELEEDPSLIST_SHOW = 'Melee DPS';
FILTER_RANGEDDPSLIST_SHOW = 'Ranged DPS';

QH_STR_MT_PRIO_LIST = 'Main Tanks';
QH_STR_MTLIST = 'Main Tanks';
QH_STR_RANGEDDPSLIST = 'Main Tanks';
QH_CLR_MTLIST = 'C';
QH_CLR_MELEEDPSLIST = 'C';
